// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcdfnkuocpnvniqvqcjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZGZua3VvY3Budm5pcXZxY2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MDk4MzMsImV4cCI6MjA0OTA4NTgzM30.JibNC9wcS1n4au1u0eaCTBGhQw5W8uZw2c_Pvw5bvfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);